version: '3.8'

services:
  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"

  # server:
  #   container_name: server
  #   build: ./server
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - PORT=5000
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules
    
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 2521 
      MYSQL_DATABASE: ATSC
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
    ports: 
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 2521 
    ports:
      - "8080:80"
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
  main-app:
  registration-app: